/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package care2all;


import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ainho
 */
public class MensajesPaciente extends javax.swing.JFrame{

    
     
      
       
    public MensajesPaciente() {
      
        initComponents();
         rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "C:\\txtcare2all\\Logo-web.gif");
         rsscalelabel.RSScaleLabel.setScaleLabel(jLabel4, "C:\\txtcare2all\\fondo2.jpg");
            ConexionSQL cSQL=new ConexionSQL();
        Connection con=cSQL.co;
        String usuario=InicioGeneral.txtUsuario.getText();
        int combo=jComboBox1.getSelectedIndex();
        String SQL="SELECT * FROM mensajes WHERE receptor='"+usuario+"'";
         String SQL1="SELECT * FROM mensajes WHERE emisor='"+usuario+"'";
         System.out.println(combo);
        
       
         try {
              Statement st = con.createStatement(); 
             if(combo==0){
         ResultSet rs=st.executeQuery(SQL);
         ResultSetMetaData rsmd=rs.getMetaData();
          int numCol=rsmd.getColumnCount();
              DefaultTableModel modelo= new DefaultTableModel();
              this.jTable1.setModel(modelo);
              for(int x=1;x<=numCol;x++){
              modelo.addColumn(rsmd.getColumnLabel(x));
              }
              
              while (rs.next()) {
               
                  Object[] fila= new Object[numCol];
                  
                  for(int y=0;y<numCol;y++){
                       fila[y]=rs.getObject(y+1);
                  }
                          modelo.addRow(fila);
                          
                          }
        }        
        if(combo==1){
             ResultSet rs1=st.executeQuery(SQL1);
             ResultSetMetaData rsmd=rs1.getMetaData();
              int numCol=rsmd.getColumnCount();
              DefaultTableModel modelo= new DefaultTableModel(){
              
                 public boolean isCellEditable(int row, int column) {
				return true;
			}
              };
              this.jTable1.setModel(modelo);
              for(int x=1;x<=numCol;x++){
              modelo.addColumn(rsmd.getColumnLabel(x));
              }
              
              while (rs1.next()) {
               
                  Object[] fila= new Object[numCol];
                  
                  for(int y=0;y<numCol;y++){
                       fila[y]=rs1.getObject(y+1);
                  }
                          modelo.addRow(fila);
                          
                          }
        }
    
           
        } catch (SQLException ex) {
            Logger.getLogger(MensajesPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
           
            
             
      }
               

             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PACIENTE GENERAL");
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 25, 90, 90));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BIENVENIDO A SU MENSAJERIA");
        jLabel10.setAutoscrolls(true);
        jLabel10.setEnabled(false);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 400, 70));

        jTable1=new javax.swing.JTable(){
            public boolean isCellEditable(int filas, int columnas){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "De", "Asunto", "Mensaje", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 280));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensajes Recibidos", "Mensajes Enviados" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 230, -1));

        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("De:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setEnabled(false);

        jLabel3.setText("Asunto: ");

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setEnabled(false);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField3.setEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        jButton2.setText("Reenviar");

        jButton3.setText("Responder");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2))))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton3)
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 400, 330));

        jButton5.setText("Nuevo mensaje");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ConexionSQL cSQL=new ConexionSQL();
        Connection con=cSQL.co;
        String usuario=InicioGeneral.txtUsuario.getText();
        int combo=jComboBox1.getSelectedIndex();
        String SQL="SELECT * FROM mensajes WHERE receptor='"+usuario+"'";
         String SQL1="SELECT * FROM mensajes WHERE emisor='"+usuario+"'";
         System.out.println(combo);
         
       
         try {
              Statement st = con.createStatement(); 
             if(combo==0){
         ResultSet rs=st.executeQuery(SQL);
         ResultSetMetaData rsmd=rs.getMetaData();
          int numCol=rsmd.getColumnCount();
              DefaultTableModel modelo= new DefaultTableModel();
              this.jTable1.setModel(modelo);
              for(int x=1;x<=numCol;x++){
              modelo.addColumn(rsmd.getColumnLabel(x));
              }
              
              while (rs.next()) {
               
                  Object[] fila= new Object[numCol];
                  
                  for(int y=0;y<numCol;y++){
                       fila[y]=rs.getObject(y+1);
                  }
                          modelo.addRow(fila);
                          
                          }
        }        
        if(combo==1){
             ResultSet rs1=st.executeQuery(SQL1);
             ResultSetMetaData rsmd=rs1.getMetaData();
              int numCol=rsmd.getColumnCount();
              DefaultTableModel modelo= new DefaultTableModel();
              this.jTable1.setModel(modelo);
              for(int x=1;x<=numCol;x++){
              modelo.addColumn(rsmd.getColumnLabel(x));
              }
              
              while (rs1.next()) {
               
                  Object[] fila= new Object[numCol];
                  
                  for(int y=0;y<numCol;y++){
                       fila[y]=rs1.getObject(y+1);
                  }
                          modelo.addRow(fila);
                          
                          }
        }
    
           
        } catch (SQLException ex) {
            Logger.getLogger(MensajesPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
           
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        
        int filaseleccionada=this.jTable1.getSelectedRow();

     try{
     
        
         
         if (filaseleccionada==-1){
         
             JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");

         }else{

           this.jTextField1.setText(jTable1.getValueAt(filaseleccionada, 1).toString());
            this.jTextField2.setText(jTable1.getValueAt(filaseleccionada, 4).toString());
               this.jTextField3.setText(jTable1.getValueAt(filaseleccionada, 3).toString());
            this.jTextArea1.setText(jTable1.getValueAt(filaseleccionada, 5).toString());
            System.out.println(jTable1.getValueAt(filaseleccionada, 6).toString());
            if(jTable1.getValueAt(filaseleccionada, 6).toString() == "false"){
                System.out.println("Entra "+jTable1.getValueAt(filaseleccionada, 6).toString());
               ConexionSQL cSQL=new ConexionSQL();
               Connection con=cSQL.co;
               System.out.println(jTable1.getValueAt(filaseleccionada, 0));
    
               String Ssql = "UPDATE mensajes SET leido='1' WHERE id='"+jTable1.getValueAt(filaseleccionada, 0)+"'";
                System.out.println(Ssql);
               
               try {
                    Statement st=con.createStatement();
                   st.executeUpdate(Ssql);
                   System.out.println("ACTUALIZADO");
                    DefaultTableModel modelo= new DefaultTableModel();
            modelo.fireTableStructureChanged(); 
                   
               } catch (SQLException ex) {
                   Logger.getLogger(MensajesPaciente.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
               

          
         }
       }catch (HeadlessException ex){

             JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);

       } 
     
     
        
        

    }//GEN-LAST:event_jTable1MousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
             int filaseleccionada=this.jTable1.getSelectedRow();
         System.out.println(jTable1.getValueAt(filaseleccionada, 6).toString());
            if(jTable1.getValueAt(filaseleccionada, 6).toString() == "true"){
                System.out.println("Entra "+jTable1.getValueAt(filaseleccionada, 6).toString());
               ConexionSQL cSQL=new ConexionSQL();
               Connection con=cSQL.co;
               System.out.println(jTable1.getValueAt(filaseleccionada, 0));
    
               String Ssql = "UPDATE mensajes SET leido='0' WHERE id='"+jTable1.getValueAt(filaseleccionada, 0)+"'";
                System.out.println(Ssql);
               
               try {
                    Statement st=con.createStatement();
                   st.executeUpdate(Ssql);
                   System.out.println("ACTUALIZADO");
                   DefaultTableModel modelo= new DefaultTableModel();
                    modelo.fireTableStructureChanged(); 
            
               } catch (SQLException ex) {
                   Logger.getLogger(MensajesPaciente.class.getName()).log(Level.SEVERE, null, ex);
               }
            }  
            
     
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajesPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajesPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajesPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajesPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MensajesPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
